### ISSUE TITLE
Navbar mobile display

### ISSUE THREAD

**Issue by Hopelezz** [LucasMERN/project-night-blog#31]
- [x] The `page layout merger` modified the navbar row orientation. The plus needs to be placed back in the center.

![image](https://user-images.githubusercontent.com/72772558/188532132-ff22f602-e552-456f-971c-72a9f3efd72d.png)

- [x] There's an issue where the logo, while `display: none` was still showing spacing. The CSS documentation says this shouldn't be doing this
> A value of display="none" indicates that the given element and its children will not be rendered. Any value other than none or inherit indicates that the given element will be rendered by the browser.

This is with the logo enabled.
![image](https://user-images.githubusercontent.com/72772558/188532349-e0600ba6-df9b-4bbc-b873-4595819c0465.png)

This might affect or be wrapped up with issue #21.

**Comment by LucasMERN** [comment]
Let the li containing the svg be the target of the display property. The ordering of the nav can be fixed by selecting the children of the list and putting the order property on them.
