### ISSUE TITLE
Viewport.css

### ISSUE THREAD

**Issue by Hopelezz** [LucasMERN/project-night-blog#34]
Tasks for setting the viewport layout across the views.

- [ ] viewContainer
- display: flex
- Flex-direction: column
- padding to get content off the walls

- [ ] headerContainer
- justify-content: center;
- text-align: center; (might need this)
- remember the profile view will house the toggle switch. May need additional step to include

- [ ] bodyContainer
- Set the size of the container? 

- [ ] subContainer 
- needs to inline the text
<img width="172" alt="image" src="https://user-images.githubusercontent.com/72772558/188705026-6ce37b06-2c52-4534-a6e6-dcdd5716e7ec.png">

**Comment by Pathholder1806** [comment]
Hey @Hopelezz !
I would like to contribute to this issue.

Just wanted to confirm that we need to add all the styles mention in the description to a new css file right and with the same class names ?

**Comment by Hopelezz** [comment]
Welcome@Pathholder1806 !Yes please, please be sure to check the pages in the views/viewport Each one of these will be affected by this file.

Here is the Design concept to show what each view will look like.
https://www.canva.com/design/DAFLMcQg6Wo/VOoLCytxatBA8HihHBSuFA/edit?utm_content=DAFLMcQg6Wo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
